# 全局配置
docker_version: "19.03.9-3.el7"
kube_version: "1.18.8"
pod_network_cidr: "10.245.0.0/16"

# Docker镜像加速器
docker_registry_mirrors:
  - "https://gqs7xcfd.mirror.aliyuncs.com"
  - "https://hub-mirror.c.163.com"

# 主机名映射
hosts_entries:
  - "192.168.2.38 k8s-master"
  - "192.168.2.40 k8s-node1"
  - "192.168.2.65 k8s-node2"