---
- name: 配置所有Kubernetes节点
  hosts: k8s_cluster
  become: yes
  roles:
    - role: common
    - role: docker
    - role: kube

- name: 初始化Master节点
  hosts: k8s_master
  become: yes
  roles:
    - role: master

- name: 加入Node节点
  hosts: k8s_nodes
  become: yes
  roles:
    - role: node

- name: 安装网络插件
  hosts: k8s_master
  become: yes
  roles:
    - role: flannel
  tasks:
    - name: 修改kube-proxy为iptables模式
      shell: |
        /usr/bin/kubectl get cm kube-proxy -n kube-system -o yaml | sed 's/mode: ""/mode: "iptables"/' | /usr/bin/kubectl apply -f -
        /usr/bin/kubectl -n kube-system rollout restart daemonsets.apps kube-proxy