---
- name: 配置所有Kubernetes节点
  hosts: k8s_cluster
  become: yes
  roles:
    - role: common
    - role: docker
    - role: kube

- name: 初始化Master节点
  hosts: k8s_master
  become: yes
  roles:
    - role: master

- name: 加入Node节点
  hosts: k8s_nodes
  become: yes
  roles:
    - role: node

- name: 安装网络插件
  hosts: k8s_master
  become: yes
  roles:
    - role: flannel
  tasks:
    - name: 修改kube-proxy为iptables模式
      shell: |
        {{ kubectl_path.stdout }} patch cm kube-proxy -n kube-system -p '{"data":{"mode":"iptables"}}'
         {{ kubectl_path.stdout }} -n kube-system rollout restart daemonset/kube-proxy