- name: 关闭防火墙
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: 清理iptables规则
  shell: iptables -F

- name: 永久关闭SELinux
  selinux:
    state: disabled
  notify: reboot_host

- name: 临时关闭SELinux
  command: setenforce 0
  when: ansible_selinux.status == "enabled"  # 仅当 SELinux 处于启用状态时执行
  ignore_errors: true

- name: 关闭Swap分区
  shell: swapoff -a

- name: 永久禁用Swap
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s.*)'
    replace: '# \1'

- name: 设置主机名
  hostname:
    name: "{{ hostname }}"

- name: 配置Hosts解析
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.2.38 k8s-master
      192.168.2.40 k8s-node1
      192.168.2.65 k8s-node2

- name: 加载内核模块
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4

- name: 加载vxlan内核模块
  modprobe:
    name: vxlan
    state: present

- name: 配置内核参数
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf

- name: 应用内核参数
  shell: sysctl --system